# Application
spring.application.name=medical-records
# H2 Console
spring.h2.console.enabled=true
# JPA
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
# DB
spring.datasource.url=jdbc:h2:mem:medicaldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# Debug
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.authentication=TRACE
